---
fs:
  folders:
    magento2:
      host: data/web/magento2
      guest: "/data/web/magento2"
    nginx:
      host: data/web/nginx/
      guest: "/data/web/nginx/"
  type: virtualbox
  disabled_folders:
    magento1:
      host: data/web/public
      guest: "/data/web/public"
hostmanager:
  extra-aliases:
  - my-custom-store-url1.local
  - my-custom-store-url2.local
magento:
  version: 2
php:
  version: 7.0
varnish:
  state: false
firewall:
  state: false
vagrant:
  box: hypernode_php7
  box_url: http://vagrant.hypernode.com/customer/php7/catalog.json
